### PR TITLE
Run aware test in test-support path

### PR DESCRIPTION
**Pull request by snewcomer**
This should merge the `test-support/*` with the consumers `test/helpers` directory, enabling users to take advantage of this run loop aware test function.

### CODE REVIEW

**Comment by toranb** [comment]
@snewcomer first I'm curious what we gain by altering that array test I see in the diff. Could we do without that change? Was it for any specific reason (consistency/ etc) or just a one off?

Also - am I correct to assume the unit tests use this helper? 2 examples below

https://github.com/toranb/ember-cli-simple-store/blob/master/tests/unit/arrays-test.js#L4
https://github.com/toranb/ember-cli-simple-store/blob/master/tests/unit/store-test.js#L5

If we move this to test support how does this still pull in from the dummy app? Just curious :)

Also -could we land on a name that is store specific (instead of plain ol' qunit) ? Maybe just using a namespace folder like `simple-store` first would help avoid some crazy conflict. In that case the import I'm thinking of would look something like ...

```js
import { test } from 'my-app/tests/helpers/simple-store/qunit'
```

**Comment by snewcomer** [comment]
I like that idea.  Another option I found is under `addon-test-support`.  `ember-native-dom-helpers` uses this pattern.  So now I would just import `ember-cli-simple-store/test-support/qunit`, which I think is exactly what you were going for above.

Also added a comment in the test-support file about passing the env to the `callback.apply` in order to solve the case where we need to maintain the test scope - i.e. `this.store setup in the beforeEach`.  So if you delete that line `let env = `, the array-test will fail.

And I think your question is about how does the test-support get utilized for a test run?  In both the addon/external application, the test-support gets merged automatically with the `/tests` folder.

**Comment by toranb** [comment]
@snewcomer love the naming choice of `addon-test-support` you are using here. The only question that remains is that callback.apply mention (why you had to use this.store in the array test). Am I correct in assuming that because this test helper (qunit) was never public api we are free to alter this and push a v5.8.0 instead of something more drastic like v6.0.0 (ie: breaking api change)

If this is the case -anything else we should consider before merging this and doing a release?

**Comment by snewcomer** [comment]
@toranb yeah I believe it is true that this was never a public api.  So without passing `testEnvironment` it will not apply any context from, say the beforeEach which may setup `this.store`/`this.ticket` etc.  So that is what I tried to emulate in the array test.

And I think given our test suite, we had something very similar you did for us before.  I refactored it to exactly what it looks like in this PR and all tests passed!  So if our test suite was an indication, I think 5.8 is good if you are good with it.  (right now our master is pointing at this PR).

**Comment by snewcomer** [comment]
Sorry actually I believe the previous `/tests/helpers/qunit` was merged into the user's test folder...if they knew it was there.  So technically it was public.  So upgrading would require a path change is all.

**Comment by toranb** [comment]
@snewcomer ah in that case ... could we do a quick deprecation + export to stay backward compat friendly? Example below of how we did this for another addon I'm supporting

https://github.com/ember-redux/ember-redux/blob/release/2x/addon/components/connect.js

also -should we avoid the refactor'd helper now that we are trying to stay backwards compatible? Still trying to understand that `this.store` change in the array test and if the older version of this qunit function would have left that test as-is (no change)

**Comment by snewcomer** [comment]
@toranb Ah great idea!  Added.

So the qunit helper as-is would not work for any test that assigned variables to the `testEnvironment`.  The original helper would not work for any test that assigned variables to `this` in the beforeEach.  Thus if this PR only changed the `array-test` to use `this.store`, it would actually fail using the existing helper.  So I see it as a +1 👍.  Lmk if you have other thoughts!

In terms of backwards compat, it did two things: 1. added support for the `testEnvironment`. and 2. refactored to use es6.  Given we replaced our test suite with the new helper, I am led to believe that this should be entirely backwards compat, but for the change in path `addon-test-support`.

**Comment by toranb** [comment]
@snewcomer thanks for all the work on this dude! I just tagged/published v5.8.0

**Pull request merged**
