### PR TITLE
[ENUMERABLE]: swap out contains for includes since contains is deprec…

### PR DESCRIPTION
**Pull request by snewcomer**
…ated somewhere around 2.8

### CODE REVIEW

**Comment by snewcomer** [comment]
sry forgot to run ember try :( .  Here is the deps warning in using `contains` fyi.  

http://emberjs.com/deprecations/v2.x/

What does it take to upgrade various pkgs btw?  I'm guessing you don't keep it at the latest, but maybe not too aggressive of an upgrade strategy?

**Comment by snewcomer** [comment]
^^ upgrading might be a better first start than getting rid of the dep warnings.

**Comment by toranb** [comment]
@snewcomer I'm happy to remove this deprecation but I'd still like to support ember 1.13/2.0 if possible for others using the addon. Can you rework this to use the polyfill mentioned in the 2.8 blog post (to help it work deprecation free for you) ?

https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill

**Comment by snewcomer** [comment]
@toranb ah that makes sense.  ^^Looks like a random fail on travis.

**Comment by toranb** [comment]
@snewcomer seems solid -works on 1.13+ :) nice work dude

**Comment by toranb** [comment]
@snewcomer I just published this as v5.1.0 :) let me know if you run into a problem

**Pull request merged**
