### PR TITLE
[REFACTOR] Removing all prototype extensions

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by toranb** [comment]
Nice update!

**Comment by williamsbdev** [comment]
Please hold on merging this as I'm working through some more changes. Thanks!

**Comment by williamsbdev** [comment]
I updated the dependencies based on what you would get out of the box with a new ember addon as of `ember-cli@0.2.3`. My goal was to remove all the prototype extensions, which has been done successfully.

**Comment by toranb** [comment]
Ah ha! awesome! thanks @williamsbdev

**Comment by toranb** [comment]
Just did the npm publish v1.0.4 (also included a tag for github/updated the changelog to point at the correct sha)

**Pull request merged**
