### PR TITLE
switch the names of the properties on a record proxy to avoid collisi…

### LINKED ISSUE #56: Find with id filter returns type of object, rather than the type property of the object
The following test fails due to the filter having a type property that is the type of the object.

```
test("find with filter does not trump type property of object", function(assert) {
  store.push("person", {
    id: 9,
    firstName: "Jarrod",
    lastName: "Taylor",
    type: "developer"
   });
  assert.equal(store.find("person", 9).get("type"), "developer");
});
```

It looks like this is due to the record-proxy having a property called type.

Gut feeling is that we should namespace the properties on this object to avoid possible collisions in the future (ex: source should be recordSource, type should be recordType).

Thoughts?

### PR DESCRIPTION
**Pull request by benkiefer**
…ons with defined values. fixes #56

### CODE REVIEW

**Comment by toranb** [comment]
Awesome - you mind altering the store/type properties in the record-array model also (for consistency mostly, no need to write a failing test as the Array returned doesn't usually have properties like store/type anyway).

I'll merge this in w/ those changes and get a bump to 4.2.0 this afternoon -sound good?

**Comment by benkiefer** [comment]
Sounds good, will do

**Comment by benkiefer** [comment]
Pushed up changes. Snagged the filtered array in there as well.

**Comment by toranb** [comment]
I just bumped this to v4.2.0 / tagged it and did the npm publish :)

let me know if you run into anything else during the big v4 upgrade you guys are doing! thanks for the quick /and complete work today!

**Pull request merged**
