### PR TITLE
Fix readme examples

### PR DESCRIPTION
**Pull request by thoov**
Just some minor readme fixes :-)

### CODE REVIEW

**Comment by toranb** [comment]
@thoov awesome! I also hope to rework this w/ the v4.0.0 release coming up

**Comment by thoov** [comment]
I was tempted to rewrite some of them in ES2015 but held off. That might be something we can do after/during the 4.0 release.

**Comment by toranb** [comment]
@thoov looks like travis-ci is being dumb today ... or that I need to upgrade from ember-cli 1.13.8 :)

**Comment by jasonmit** [comment]
@toranb it's the breaking jQuery change.  I fixed it here: https://github.com/toranb/ember-cli-simple-store/commit/3e78542a685bf398711cb2758c7587b043816e48

This is safe to merge since it's a README change

**Pull request merged**
